version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout
      - restore_cache:
          key: repo-{{ checksum "build.gradle" }}

      - run:
          name: Download dependencies
          command: ./gradle dependencies

      - run:
          name: Download jpm
          command: |
            curl https://www.jpm4j.org/install/script | sh
            jpm install com.codacy:codacy-coverage-reporter:assembly

      - save_cache:
          paths:
            - ~/.m2
          key: repo-{{ checksum "build.gradle" }}

      - persist_to_workspace:
          root: .
          paths: .

  test:
    working_directory: ~/repo

    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - attach_workspace:
        at: .

      - restore_cache:
          key: repo-{{ checksum "build.gradle" }}

      - run:
          name: Run tests
          command: |
            codacy-coverage-reporter -l Java -r coverage.xml
            jpm install com.codacy:codacy-coverage-reporter:assembly
            gradle jacocoTestReport
            bash <(curl -s https://codecov.io/bash)

      - store_test_results:
          path: ~/repo/test_reports

workflows:
  version: 2
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build
